version: 2
jobs:
  build:
    working_directory: ~/iconfont
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm to latest version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - store_artifacts:
          path: artifacts
          destination: /
      - deploy:
          name: Run a npm publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish
            fi