version: 2
jobs:
  build:
    working_directory: /home/circleci/iconfont
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies via yarn
          command: yarn install
      - run:
          name: Install gulp task runner
          command: sudo yarn global add gulp-cli
      - run:
          name: Run font build process
          command: gulp
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "~/.yarn-cache"
            - .node_modules
      - store_artifacts:
          path: artifacts
          destination: /
      - deploy:
          name: Run a npm publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish
            fi